appname: "DocuStore"
layout: "main"
charset: "UTF-8"
template: "template_toolkit"
engines:
  template_toolkit:
    start_tag: '[%'
    end_tag:   '%]'
plugins:
  DBIC:
    default:
      dsn: 'dbi:SQLite:data.sqlite'
      schema_class: 'AppName::Schema'
      options:
        sqlite_unicode: 1
